name: Nightly Builds

on:
  schedule:
    - cron: '0 3 * * 6'  # Runs every day at 03:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [xiaomi-curtana.cfg, xiaomi-joyeuse.cfg]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git fakeroot ccache unzip
          pip3 install --user pmbootstrap
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Copy pmbootstrap config
        run: |
          mkdir -p ~/.config
          cp "${{ matrix.config }}" ~/.config/pmbootstrap.cfg

      - name: Initialize pmbootstrap
        run: |
          pmbootstrap init --config ~/.config/pmbootstrap.cfg --no-keygen --no-bootstrap --force

      - name: Build rootfs and boot.img
        run: |
          pmbootstrap install
          pmbootstrap install --image

      - name: Export images
        run: |
          pmbootstrap export
          mkdir -p out
          cp ~/.local/var/pmbootstrap/export/* out/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config }}-build
          path: out/
          
