name: Build images

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at midnight

env:
  KERNEL_BRANCH: 6.12.1

jobs:
  build-image:
    strategy:
      matrix:
        device: [curtana, joyeuse]

    runs-on: ubuntu-latest
    name: Build ${{ matrix.device }}

    steps:
      - name: Enable verbose shell
        run: set -x

      - name: Check out build configurations
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap from git
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Create pmbootstrap config file (skip init)
        run: |
          mkdir -p ~/.config
          cat > ~/.config/pmbootstrap_v3.cfg <<EOF
[general]
channel=edge
device=xiaomi-${{ matrix.device }}
kernel=linux-postmarketos-qcom-sm7125
ui=phosh
use_systemd=false
EOF

      - name: Set up pmaports
        run: |
          echo -e '\n\n' | pmbootstrap pull
          cd ~/.local/var/pmbootstrap/cache_git/pmaports || git clone https://gitlab.postmarketos.org/postmarketOS/pmaports.git ~/.local/var/pmbootstrap/cache_git/pmaports
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote add sm7125 https://github.com/sm7125-mainline/pmaports.git || true
          DEFAULT_BRANCH=$(git remote show sm7125 | awk '/HEAD branch/ {print $NF}')
          git fetch sm7125 $DEFAULT_BRANCH
          git reset --hard sm7125/$DEFAULT_BRANCH

      - name: Pull latest packages (required!)
        run: pmbootstrap pull

      - name: Check kernel branch (only for curtana)
        if: matrix.device == 'curtana'
        run: |
          DEFAULT_BRANCH=$(curl -s https://api.github.com/repos/sm7125-mainline/linux | jq -r '.default_branch')
          echo "Default branch is $DEFAULT_BRANCH"
          echo "KERNEL_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Clone kernel sources (only for curtana)
        if: matrix.device == 'curtana'
        run: |
          git clone https://github.com/sm7125-mainline/linux.git --single-branch --branch ${{ env.KERNEL_BRANCH }} --depth 1 ./linux

      - name: Compile kernel with envkernel (only for curtana)
        if: matrix.device == 'curtana'
        run: |
          cd linux
          shopt -s expand_aliases
          source ../pmbootstrap/helpers/envkernel.sh
          make defconfig sm7125.config
          make -j$(nproc)
          pmbootstrap build --envkernel linux-postmarketos-qcom-sm7125

      - name: Create artifact directory
        run: mkdir -p out

      - name: Build device rootfs and export images
        run: |
          cp xiaomi-${{ matrix.device }}.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-${{ matrix.device }}.img
          cp /tmp/postmarketOS-export/xiaomi-miatoll.img out/rootfs-xiaomi-${{ matrix.device }}.img
          sed -i 's/tianma/huaxing/g' ~/.config/pmbootstrap_v3.cfg
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-huaxing-${{ matrix.device }}.img
          xz -T0 -9e -v out/rootfs-xiaomi-${{ matrix.device }}.img
          echo -e "n\nn\ny\n" | pmbootstrap zap

      - name: Show output files
        run: ls -lh out/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-${{ matrix.device }}-${{ env.KERNEL_BRANCH }}
          path: out/*
          retention-days: 7
