name: Nightly Builds

on:
  schedule:
    - cron: '0 3 * * 0' # Every Sunday at 3 AM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [xiaomi-joyeuse, xiaomi-curtana]
    env:
      PMOS_FORCE_KEYGEN: 1

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip curl git
          pip3 install --user pmbootstrap
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clone kernel source
        run: |
          git clone https://github.com/sm7125-mainline/linux.git --single-branch --branch main --depth 1 linux

      - name: Init pmbootstrap
        run: |
          mkdir -p ~/.config
          cp configs/${{ matrix.device }}.cfg ~/.config/pmbootstrap.cfg
          pmbootstrap init --no-keygen --config ~/.config/pmbootstrap.cfg

      - name: Build image
        run: |
          pmbootstrap install --device=${{ matrix.device }}
          pmbootstrap export

      - name: Package output
        run: |
          mkdir -p output
          zip -j output/${{ matrix.device }}.zip ~/.local/var/pmbootstrap/chroot_rootfs_${{ matrix.device }}/boot.img \
            ~/.local/var/pmbootstrap/chroot_rootfs_${{ matrix.device }}/rootfs.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}-build
          path: output/${{ matrix.device }}.zip
          
