name: Build Nightly pmOS Images

on:
  schedule:
    - cron: '0 3 * * 0'  # every Sunday at 3AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: [xiaomi-curtana, xiaomi-joyeuse]

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            abootimg android-sdk-libsparse-utils bc bison build-essential \
            cpio curl device-tree-compiler flex git libssl-dev make \
            python3 python3-pip rsync tar unzip wget xz-utils

      - name: Install pmbootstrap
        run: |
          pip3 install --user pmbootstrap
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Clone pmaports
        run: |
          git clone https://gitlab.com/postmarketOS/pmaports.git ~/.local/var/pmbootstrap/cache_git/pmaports

      - name: Init pmbootstrap
        run: |
          cp "${{ matrix.device }}.cfg" ~/.config/pmbootstrap.cfg
          pmbootstrap init --no-keygen

      - name: Clone kernel (sm7125-mainline)
        run: |
          git clone https://github.com/sm7125-mainline/linux.git \
            --single-branch --branch main --depth 1 ./linux
          mkdir -p ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/${{ matrix.device }}
          cp -r ./linux/* ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/${{ matrix.device }}/

      - name: Build packages
        run: |
          pmbootstrap build linux-${{ matrix.device }}
          pmbootstrap build device-${{ matrix.device }}

      - name: Install system
        run: |
          pmbootstrap install --device=${{ matrix.device }}

      - name: Create boot image and export
        run: |
          pmbootstrap initfs hook_add boot encryption
          pmbootstrap install --android-recovery-zip
          pmbootstrap export

      - name: Pack ZIP
        run: |
          mkdir -p output/${{ matrix.device }}
          cp ~/.local/var/pmbootstrap/chroot_native/home/pmos/export/* output/${{ matrix.device }}/
          cd output && zip -r ${{ matrix.device }}.zip ${{ matrix.device }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.device }}-zip
          path: output/${{ matrix.device }}.zip
