name: Build images
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # Every Friday at midnight

env:
  KERNEL_BRANCH: 6.12.1

jobs:
  build-image:
    strategy:
      matrix:
        version: ["default"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Substitute placeholders in configs
        run: |
          find . -type f -name "*.cfg" -exec sed -i "s|HOME|$(echo $HOME)|;s|NPROC|$(nproc)|" {} +

      - name: Install pmbootstrap and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel jq libffi-dev libssl-dev
          pip3 install --upgrade --user pmbootstrap
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          pmbootstrap --version

      - name: Prepare pmbootstrap config
        run: |
          mkdir -p ~/.config
          cp xiaomi-curtana.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap init --no-interactive --configfile ~/.config/pmbootstrap_v3.cfg

      - name: Pull latest pmaports and repositories
        run: pmbootstrap pull

      - name: Fetch kernel default branch dynamically (override env)
        if: matrix.version == 'default'
        run: |
          DEFAULT_BRANCH=$(curl -s https://api.github.com/repos/sm7125-mainline/linux | jq -r '.default_branch')
          echo "KERNEL_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Clone kernel sources
        run: |
          git clone https://github.com/sm7125-mainline/linux.git --single-branch --branch ${{ env.KERNEL_BRANCH }} --depth 1 linux

      - name: Compile kernel with envkernel
        run: |
          cd linux
          shopt -s expand_aliases
          source ../pmbootstrap/helpers/envkernel.sh
          make defconfig sm7125.config
          make -j$(nproc)
          pmbootstrap build --envkernel linux-postmarketos-qcom-sm7125

      - name: Create artifact directory
        run: mkdir -p out

      - name: Build Xiaomi Curtana images
        run: |
          cp xiaomi-curtana.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-curtana.img
          cp /tmp/postmarketOS-export/xiaomi-miatoll.img out/rootfs-xiaomi-curtana.img
          sed -i 's/tianma/huaxing/g' ~/.config/pmbootstrap_v3.cfg
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-huaxing-curtana.img
          xz -T0 -9e -v out/rootfs-xiaomi-curtana.img
          echo -e "n\nn\ny\n" | pmbootstrap zap

      - name: Upload Xiaomi Curtana artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-curtana-${{ env.KERNEL_BRANCH }}
          path: out/*-curtana.img*
          retention-days: 7

      - name: Build Xiaomi Joyeuse images
        run: |
          cp xiaomi-joyeuse.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap install --password 147147
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-joyeuse.img
          cp /tmp/postmarketOS-export/xiaomi-miatoll.img out/rootfs-xiaomi-joyeuse.img
          sed -i 's/tianma/huaxing/g' ~/.config/pmbootstrap_v3.cfg
          pmbootstrap export
          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-huaxing-joyeuse.img
          xz -T0 -9e -v out/rootfs-xiaomi-joyeuse.img
          echo -e "n\nn\ny\n" | pmbootstrap zap

      - name: Upload Xiaomi Joyeuse artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-joyeuse-${{ env.KERNEL_BRANCH }}
          path: out/*-joyeuse.img*
          retention-days: 7
          
